name: ci cd

on:
  push

permissions:
  contents: read

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test
        run: |
          pytest
        
        

  cd:

    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SSH client
        run: sudo apt-get install -y sshpass
      - name: connect to vm
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no azuruser@137.117.127.213
          echo "App updated successfully"
      - name: install apps to vm
        run: |
          sudo apt update
          sudo apt-get install -y git 
          sudo apt-get install -y python3
          sudo apt install -y python3-pip
      - name: upload the app
        run: |
          sudo mkdir -p /home/azureuser/app 
          cd /home/azureuser/app 
          if [ -d orientation-python ]; then
            rm -r orientation-python
          git clone https://github.com/shaniblau/orientation-python.git
          cd orientation-python
          pip install -r requirements.txt 
          python3 main.py
        shell: bash
          
